"""
Upload Planview demo videos to YouTube using the official API.

Requirements
============

.. code-block:: bash

   pip install google-api-python-client google-auth-oauthlib google-auth-httplib2

Usage
=====

.. code-block:: bash

   # Option 1: edit RUN_LIMIT / RUN_DRY_RUN below and press Play in VS Code
   python codes/upload_planview_demos_to_youtube.py

   # Option 2: CLI
   python codes/upload_planview_demos_to_youtube.py
   python codes/upload_planview_demos_to_youtube.py --limit 3
   python codes/upload_planview_demos_to_youtube.py --dry-run

Notes
=====

This module is intentionally specific to the JSON files generated by
``codes/scrapping_planviews_demos.py`` and to the one-off upload flow
requested for Planview demos.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
import re
import sys
from typing import Any


LOGGER = logging.getLogger("upload_planview_demos_to_youtube")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"
OUTPUT_ROOT = PROJECT_ROOT / "out" / "scrapping"

TOKEN_FILE_DEFAULT = PROJECT_ROOT / "out" / "youtube_upload" / "token.json"

RUN_LIMIT: int | None = None
RUN_DRY_RUN = False

YOUTUBE_UPLOAD_COST = 100
YOUTUBE_PLAYLIST_ITEM_INSERT_COST = 50
YOUTUBE_PLAYLIST_CREATE_COST = 50

YOUTUBE_SCOPES = (
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.force-ssl",
)

TITLE_MAX_CHARS = 100
DESCRIPTION_MAX_BYTES = 5000


class QuotaBudgetExceeded(RuntimeError):
    """Raised when the configured daily quota budget would be exceeded."""


@dataclass(frozen=True)
class CategoryConfig:
    """Static configuration per JSON file."""

    name: str
    json_path: Path
    playlist_id_key: str
    playlist_title_key: str


CATEGORY_CONFIGS = (
    CategoryConfig(
        name="product_demos",
        json_path=OUTPUT_ROOT / "product_demos.json",
        playlist_id_key="YOUTUBE_PRODUCT_PLAYLIST_ID",
        playlist_title_key="YOUTUBE_PRODUCT_PLAYLIST_TITLE",
    ),
    CategoryConfig(
        name="solution_demos",
        json_path=OUTPUT_ROOT / "solution_demos.json",
        playlist_id_key="YOUTUBE_SOLUTION_PLAYLIST_ID",
        playlist_title_key="YOUTUBE_SOLUTION_PLAYLIST_TITLE",
    ),
)


def utc_now_iso() -> str:
    """Return the current UTC timestamp."""

    return datetime.now(timezone.utc).isoformat()


def load_env_file(path: Path) -> dict[str, str]:
    """Load a minimal .env file without extra dependencies."""

    if not path.exists():
        raise FileNotFoundError(
            f"No se encontro {path}. Crea tu .env a partir de .env_example antes de subir videos."
        )

    env: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith(("'", '"')) and value.endswith(("'", '"')) and len(value) >= 2:
            value = value[1:-1]
        env[key] = value
    return env


def env_get(env: dict[str, str], key: str, default: str | None = None) -> str | None:
    """Return an env value stripped, treating empty strings as missing."""

    value = env.get(key, default)
    if value is None:
        return None
    value = value.strip()
    return value or None


def env_get_bool(env: dict[str, str], key: str, default: bool = False) -> bool:
    """Parse a boolean env value."""

    value = env_get(env, key)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_get_int(env: dict[str, str], key: str, default: int | None = None) -> int | None:
    """Parse an integer env value."""

    value = env_get(env, key)
    if value is None:
        return default
    return int(value)


def resolve_repo_path(value: str | None, fallback: Path | None = None) -> Path | None:
    """Resolve a path relative to the repository root."""

    if value is None:
        return fallback
    candidate = Path(value).expanduser()
    if not candidate.is_absolute():
        candidate = PROJECT_ROOT / candidate
    return candidate


def import_google_components() -> dict[str, Any]:
    """Import Google client libraries lazily."""

    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
    except ImportError as exc:
        raise RuntimeError(
            "Faltan dependencias de Google. Instala: "
            "'pip install google-api-python-client google-auth-oauthlib google-auth-httplib2'"
        ) from exc

    return {
        "Request": Request,
        "Credentials": Credentials,
        "InstalledAppFlow": InstalledAppFlow,
        "build": build,
        "MediaFileUpload": MediaFileUpload,
    }


def load_store(config: CategoryConfig) -> dict[str, Any]:
    """Load one of the scraping JSON stores."""

    if not config.json_path.exists():
        raise FileNotFoundError(f"No existe el JSON esperado: {config.json_path}")
    with config.json_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def sort_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Sort entries in a stable, predictable order."""

    return sorted(
        items,
        key=lambda item: (
            int(item.get("listing_position") or 10**9),
            str(item.get("card_id") or ""),
        ),
    )


def summarize_store(store: dict[str, Any]) -> dict[str, Any]:
    """Build top-level stats for the upload stage."""

    items = store.get("items", [])
    uploaded = sum(1 for item in items if item.get("youtube_uploaded"))
    pending_upload = sum(1 for item in items if is_ready_for_upload(item) and not item.get("youtube_uploaded"))
    pending_playlist = sum(
        1
        for item in items
        if item.get("youtube_uploaded") and item.get("youtube_video_id") and not item.get("youtube_playlist_item_id")
    )
    return {
        "total_items": len(items),
        "youtube_uploaded": uploaded,
        "youtube_pending_upload": pending_upload,
        "youtube_pending_playlist": pending_playlist,
    }


def save_store(config: CategoryConfig, store: dict[str, Any]) -> None:
    """Write a JSON store atomically."""

    store["items"] = sort_items(store.get("items", []))
    store["updated_at"] = utc_now_iso()
    store.setdefault("stats", {})
    store["stats"]["youtube"] = summarize_store(store)

    temp_path = config.json_path.with_suffix(config.json_path.suffix + ".tmp")
    with temp_path.open("w", encoding="utf-8") as handle:
        json.dump(store, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    temp_path.replace(config.json_path)


def ensure_youtube_fields(entry: dict[str, Any]) -> None:
    """Ensure upload-related fields exist in a JSON entry."""

    entry.setdefault("youtube_uploaded", False)
    entry.setdefault("youtube_video_id", None)
    entry.setdefault("youtube_video_url", None)
    entry.setdefault("youtube_playlist_id", None)
    entry.setdefault("youtube_playlist_item_id", None)
    entry.setdefault("youtube_uploaded_at", None)
    entry.setdefault("youtube_upload_error", None)
    entry.setdefault("youtube_title_used", None)
    entry.setdefault("youtube_description_used", None)
    entry.setdefault("youtube_privacy_status", None)


def set_upload_error(entry: dict[str, Any], error: Exception | str, *, stage: str) -> None:
    """Store the latest upload-related error on the entry."""

    if isinstance(error, Exception):
        error_type = error.__class__.__name__
        message = str(error)
    else:
        error_type = "Error"
        message = str(error)

    entry["youtube_upload_error"] = {
        "timestamp": utc_now_iso(),
        "stage": stage,
        "type": error_type,
        "message": message.strip(),
    }


def clear_upload_error(entry: dict[str, Any]) -> None:
    """Clear the upload error marker after a successful step."""

    entry["youtube_upload_error"] = None


def is_ready_for_upload(entry: dict[str, Any]) -> bool:
    """Return True when a JSON entry has a local video file ready."""

    video_path = entry.get("video_path")
    return bool(video_path and Path(video_path).exists())


def normalize_spaces(value: str | None) -> str:
    """Collapse whitespace in a string."""

    if not value:
        return ""
    return re.sub(r"\s+", " ", value).strip()


def sanitize_youtube_title(entry: dict[str, Any]) -> str:
    """Build a YouTube-safe title from the JSON entry."""

    base_title = (
        entry.get("demo_title")
        or entry.get("card_title")
        or Path(str(entry.get("video_path") or "video")).stem
    )
    title = normalize_spaces(str(base_title))
    title = title.replace("<", "-").replace(">", "-")
    title = re.sub(r"[\x00-\x1F\x7F]", "", title)
    if len(title) > TITLE_MAX_CHARS:
        title = title[:TITLE_MAX_CHARS].rstrip()
    if not title:
        title = "Planview demo"
    return title


def trim_utf8_bytes(value: str, max_bytes: int) -> str:
    """Trim a string to a maximum UTF-8 byte length."""

    encoded = value.encode("utf-8")
    if len(encoded) <= max_bytes:
        return value
    trimmed = encoded[:max_bytes]
    while True:
        try:
            return trimmed.decode("utf-8").rstrip()
        except UnicodeDecodeError:
            trimmed = trimmed[:-1]


def sanitize_youtube_description(entry: dict[str, Any]) -> str:
    """Build a YouTube-safe description from the JSON entry."""

    description = entry.get("demo_description") or entry.get("card_summary") or ""
    description = str(description).replace("<", "-").replace(">", "-")
    description = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", "", description)
    description = description.strip()
    return trim_utf8_bytes(description, DESCRIPTION_MAX_BYTES)


def validate_privacy_status(value: str | None) -> str:
    """Validate the requested privacy status."""

    privacy_status = (value or "unlisted").strip().lower()
    if privacy_status not in {"public", "private", "unlisted"}:
        raise ValueError("YOUTUBE_VIDEO_PRIVACY_STATUS debe ser public, private o unlisted.")
    return privacy_status


def validate_playlist_privacy_status(value: str | None) -> str:
    """Validate playlist privacy."""

    privacy_status = (value or "unlisted").strip().lower()
    if privacy_status not in {"public", "private", "unlisted"}:
        raise ValueError("YOUTUBE_PLAYLIST_PRIVACY_STATUS debe ser public, private o unlisted.")
    return privacy_status


def load_client_config(env: dict[str, str]) -> tuple[dict[str, Any] | None, Path | None]:
    """Load OAuth client configuration from file or from env vars."""

    client_secrets_file = resolve_repo_path(env_get(env, "YOUTUBE_CLIENT_SECRETS_FILE"))
    if client_secrets_file:
        if not client_secrets_file.exists():
            raise FileNotFoundError(f"No existe YOUTUBE_CLIENT_SECRETS_FILE: {client_secrets_file}")
        return None, client_secrets_file

    client_id = env_get(env, "YOUTUBE_CLIENT_ID")
    client_secret = env_get(env, "YOUTUBE_CLIENT_SECRET")
    if not client_id or not client_secret:
        raise ValueError(
            "Debes definir YOUTUBE_CLIENT_SECRETS_FILE o bien YOUTUBE_CLIENT_ID y YOUTUBE_CLIENT_SECRET en .env."
        )

    client_config = {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": ["http://localhost"],
        }
    }
    return client_config, None


def get_authenticated_service(env: dict[str, str], google: dict[str, Any]) -> Any:
    """Authenticate the user and build the YouTube API client."""

    Request = google["Request"]
    Credentials = google["Credentials"]
    InstalledAppFlow = google["InstalledAppFlow"]
    build = google["build"]

    token_file = resolve_repo_path(env_get(env, "YOUTUBE_TOKEN_FILE"), TOKEN_FILE_DEFAULT)
    assert token_file is not None
    token_file.parent.mkdir(parents=True, exist_ok=True)

    credentials = None
    if token_file.exists():
        credentials = Credentials.from_authorized_user_file(str(token_file), YOUTUBE_SCOPES)

    if credentials and credentials.valid:
        return build("youtube", "v3", credentials=credentials, cache_discovery=False)

    if credentials and credentials.expired and credentials.refresh_token:
        credentials.refresh(Request())
    else:
        client_config, client_secrets_file = load_client_config(env)
        if client_secrets_file is not None:
            flow = InstalledAppFlow.from_client_secrets_file(str(client_secrets_file), YOUTUBE_SCOPES)
        else:
            assert client_config is not None
            flow = InstalledAppFlow.from_client_config(client_config, YOUTUBE_SCOPES)
        credentials = flow.run_local_server(port=0)

    token_file.write_text(credentials.to_json(), encoding="utf-8")
    return build("youtube", "v3", credentials=credentials, cache_discovery=False)


def consume_quota(quota_state: dict[str, int | None], amount: int, reason: str) -> None:
    """Consume estimated quota or stop before exceeding the budget."""

    budget = quota_state.get("budget")
    used = int(quota_state.get("used") or 0)
    if budget is not None and used + amount > budget:
        raise QuotaBudgetExceeded(
            f"Se alcanzaria el presupuesto diario de cuota ({used}+{amount}>{budget}) antes de {reason}."
        )
    quota_state["used"] = used + amount


def list_user_playlists(youtube: Any) -> list[dict[str, Any]]:
    """List all playlists of the authenticated user."""

    playlists: list[dict[str, Any]] = []
    page_token: str | None = None
    while True:
        response = (
            youtube.playlists()
            .list(part="snippet,status", mine=True, maxResults=50, pageToken=page_token)
            .execute()
        )
        playlists.extend(response.get("items", []))
        page_token = response.get("nextPageToken")
        if not page_token:
            break
    return playlists


def find_playlist_by_title(youtube: Any, title: str) -> str | None:
    """Find a playlist by exact title match."""

    wanted = normalize_spaces(title).lower()
    for playlist in list_user_playlists(youtube):
        current = normalize_spaces(playlist.get("snippet", {}).get("title", "")).lower()
        if current == wanted:
            return playlist.get("id")
    return None


def create_playlist(
    youtube: Any,
    title: str,
    privacy_status: str,
    *,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> str:
    """Create a playlist for one category."""

    consume_quota(quota_state, YOUTUBE_PLAYLIST_CREATE_COST, f"crear playlist '{title}'")
    if dry_run:
        fake_id = f"dry_run_{re.sub(r'[^a-z0-9]+', '_', title.lower()).strip('_') or 'playlist'}"
        LOGGER.info("DRY RUN: se crearia playlist '%s' con id %s", title, fake_id)
        return fake_id

    response = (
        youtube.playlists()
        .insert(
            part="snippet,status",
            body={
                "snippet": {"title": title},
                "status": {"privacyStatus": privacy_status},
            },
        )
        .execute()
    )
    return response["id"]


def resolve_playlist_id(
    youtube: Any,
    env: dict[str, str],
    config: CategoryConfig,
    *,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> str:
    """Resolve or create the playlist for one category."""

    configured_id = env_get(env, config.playlist_id_key)
    if configured_id:
        return configured_id

    playlist_title = env_get(env, config.playlist_title_key)
    if not playlist_title:
        raise ValueError(f"Falta {config.playlist_title_key} en .env.")

    existing_id = find_playlist_by_title(youtube, playlist_title)
    if existing_id:
        LOGGER.info("%s: se reutilizara playlist existente '%s' (%s).", config.name, playlist_title, existing_id)
        return existing_id

    if not env_get_bool(env, "YOUTUBE_CREATE_PLAYLISTS_IF_MISSING", default=True):
        raise ValueError(
            f"No existe playlist para {config.name} y YOUTUBE_CREATE_PLAYLISTS_IF_MISSING esta en false."
        )

    playlist_privacy = validate_playlist_privacy_status(env_get(env, "YOUTUBE_PLAYLIST_PRIVACY_STATUS"))
    playlist_id = create_playlist(
        youtube,
        playlist_title,
        playlist_privacy,
        dry_run=dry_run,
        quota_state=quota_state,
    )
    LOGGER.info("%s: playlist creada '%s' (%s).", config.name, playlist_title, playlist_id)
    return playlist_id


def upload_video_file(
    youtube: Any,
    google: dict[str, Any],
    entry: dict[str, Any],
    env: dict[str, str],
    *,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> tuple[str, str, str]:
    """Upload a local video file to YouTube."""

    consume_quota(quota_state, YOUTUBE_UPLOAD_COST, f"subir video {entry.get('card_id')}")

    title = sanitize_youtube_title(entry)
    description = sanitize_youtube_description(entry)
    privacy_status = validate_privacy_status(env_get(env, "YOUTUBE_VIDEO_PRIVACY_STATUS"))
    category_id = env_get(env, "YOUTUBE_VIDEO_CATEGORY_ID", "22") or "22"
    made_for_kids = env_get_bool(env, "YOUTUBE_MADE_FOR_KIDS", default=False)
    notify_subscribers = env_get_bool(env, "YOUTUBE_NOTIFY_SUBSCRIBERS", default=False)

    if dry_run:
        fake_video_id = f"dry_run_video_{entry.get('resource_id')}"
        LOGGER.info("DRY RUN: se subiria %s como '%s'.", entry.get("video_path"), title)
        return fake_video_id, title, description

    MediaFileUpload = google["MediaFileUpload"]

    request = youtube.videos().insert(
        part="snippet,status",
        notifySubscribers=notify_subscribers,
        body={
            "snippet": {
                "title": title,
                "description": description,
                "categoryId": category_id,
            },
            "status": {
                "privacyStatus": privacy_status,
                "selfDeclaredMadeForKids": made_for_kids,
            },
        },
        media_body=MediaFileUpload(str(Path(entry["video_path"])), chunksize=8 * 1024 * 1024, resumable=True),
    )

    response = None
    while response is None:
        _, response = request.next_chunk()

    return response["id"], title, description


def add_video_to_playlist(
    youtube: Any,
    playlist_id: str,
    video_id: str,
    *,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> str:
    """Add an uploaded video to a playlist."""

    consume_quota(quota_state, YOUTUBE_PLAYLIST_ITEM_INSERT_COST, f"agregar {video_id} a playlist")
    if dry_run:
        fake_item_id = f"dry_run_playlist_item_{video_id}"
        LOGGER.info("DRY RUN: se agregaria %s a playlist %s.", video_id, playlist_id)
        return fake_item_id

    response = (
        youtube.playlistItems()
        .insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": video_id,
                    },
                }
            },
        )
        .execute()
    )
    return response["id"]


def process_entry_upload(
    youtube: Any,
    google: dict[str, Any],
    env: dict[str, str],
    entry: dict[str, Any],
    playlist_id: str,
    *,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> None:
    """Upload one entry and attach it to the target playlist."""

    ensure_youtube_fields(entry)

    if not is_ready_for_upload(entry):
        return

    video_id = entry.get("youtube_video_id")
    if not entry.get("youtube_uploaded"):
        video_id, title_used, description_used = upload_video_file(
            youtube,
            google,
            entry,
            env,
            dry_run=dry_run,
            quota_state=quota_state,
        )
        entry["youtube_uploaded"] = True
        entry["youtube_video_id"] = video_id
        entry["youtube_video_url"] = f"https://www.youtube.com/watch?v={video_id}"
        entry["youtube_uploaded_at"] = utc_now_iso()
        entry["youtube_title_used"] = title_used
        entry["youtube_description_used"] = description_used
        entry["youtube_privacy_status"] = validate_privacy_status(env_get(env, "YOUTUBE_VIDEO_PRIVACY_STATUS"))
        clear_upload_error(entry)

    if entry.get("youtube_uploaded") and not entry.get("youtube_playlist_item_id"):
        assert video_id is not None
        playlist_item_id = add_video_to_playlist(
            youtube,
            playlist_id,
            video_id,
            dry_run=dry_run,
            quota_state=quota_state,
        )
        entry["youtube_playlist_id"] = playlist_id
        entry["youtube_playlist_item_id"] = playlist_item_id
        clear_upload_error(entry)


def upload_category(
    youtube: Any,
    google: dict[str, Any],
    env: dict[str, str],
    config: CategoryConfig,
    *,
    limit: int | None,
    dry_run: bool,
    quota_state: dict[str, int | None],
) -> None:
    """Upload all pending entries for one category."""

    store = load_store(config)
    for entry in store.get("items", []):
        ensure_youtube_fields(entry)
    save_store(config, store)

    playlist_id = resolve_playlist_id(
        youtube,
        env,
        config,
        dry_run=dry_run,
        quota_state=quota_state,
    )

    items = sort_items(store.get("items", []))
    if limit is not None:
        items = items[:limit]

    initial_summary = summarize_store(store)
    LOGGER.info("%s: estado inicial %s", config.name, initial_summary)

    processed = 0
    for entry in items:
        if not is_ready_for_upload(entry):
            continue
        if entry.get("youtube_uploaded") and entry.get("youtube_playlist_item_id"):
            continue

        processed += 1
        try:
            process_entry_upload(
                youtube,
                google,
                env,
                entry,
                playlist_id,
                dry_run=dry_run,
                quota_state=quota_state,
            )
        except QuotaBudgetExceeded:
            save_store(config, store)
            raise
        except Exception as exc:
            set_upload_error(entry, exc, stage="youtube_upload")
        finally:
            save_store(config, store)

    if processed == 0:
        LOGGER.info("%s: no hay videos pendientes por subir o enlazar a playlist.", config.name)

    final_summary = summarize_store(store)
    LOGGER.info("%s: estado final %s", config.name, final_summary)


def validate_run_configuration() -> None:
    """Validate no-args execution settings."""

    if RUN_LIMIT is not None and RUN_LIMIT <= 0:
        raise ValueError("RUN_LIMIT debe ser None o un entero positivo.")


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description="Sube videos de Planview a YouTube usando la API oficial.")
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Sube solo los primeros N videos pendientes por categoria.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="No sube nada; solo simula acciones y consume cuota estimada localmente.",
    )
    args = parser.parse_args(argv)
    if args.limit is not None and args.limit <= 0:
        parser.error("--limit debe ser un entero positivo.")
    return args


def main(argv: list[str] | None = None) -> int:
    """Program entry point."""

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )

    effective_argv = list(sys.argv[1:] if argv is None else argv)
    if not effective_argv:
        validate_run_configuration()
        limit = RUN_LIMIT
        dry_run = RUN_DRY_RUN
    else:
        args = parse_args(effective_argv)
        limit = args.limit
        dry_run = args.dry_run

    LOGGER.info("Ejecutando upload a YouTube limit=%s dry_run=%s env=%s", limit, dry_run, ENV_PATH)

    env = load_env_file(ENV_PATH)
    google = import_google_components()
    youtube = get_authenticated_service(env, google)

    quota_budget = env_get_int(env, "YOUTUBE_DAILY_QUOTA_BUDGET", default=10_000)
    if quota_budget is not None and quota_budget <= 0:
        quota_budget = None
    quota_state: dict[str, int | None] = {"used": 0, "budget": quota_budget}

    try:
        for config in CATEGORY_CONFIGS:
            upload_category(
                youtube,
                google,
                env,
                config,
                limit=limit,
                dry_run=dry_run,
                quota_state=quota_state,
            )
    except QuotaBudgetExceeded as exc:
        LOGGER.warning("%s", exc)
        LOGGER.warning("Cuota estimada usada en esta corrida: %s", quota_state.get("used"))
        return 2

    LOGGER.info("Proceso terminado. Cuota estimada usada en esta corrida: %s", quota_state.get("used"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
